########################################### 默认数据源配置 ###########################################
defaultDs:
  string:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driverClassName: ${datasource.driverClassName}
    connection-init-sqls: ${datasource.connectionInitSqls}
    validationQuery: ${datasource.validationQuery:select 1}
    filters: ${datasource.filters:stat}
  int:
    initialSize: ${datasource.initialSize:20}
    minIdle: ${datasource.minIdle:20}
    maxActive: ${datasource.maxActive:50}
    maxPoolPreparedStatementPerConnectionSize: ${datasource.maxPoolPreparedStatementPerConnectionSize:20}
  long:
    maxWait: ${datasource.maxWait:120000}
    timeBetweenEvictionRunsMillis: ${datasource.timeBetweenEvictionRunsMillis:60000}
    minEvictableIdleTimeMillis: ${datasource.minEvictableIdleTimeMillis:300000}
  boolean:
    testWhileIdle: ${datasource.testWhileIdle:true}
    testOnBorrow: ${datasource.testOnBorrow:true}
    testOnReturn: ${datasource.testOnReturn:false}
    poolPreparedStatements: ${datasource.poolPreparedStatements:true}


########################################### 应用服务配置 #############################################

################ mybatis 配置
mybatis:
  ## mybatis mapper 扫描路径
  mapper-locations: ${mybatis.mapper-locations:classpath*:/mapper/**/*Mapper.xml}

################ seata 配置
seata:
  enabled: ${seata.enabled:true}

################ 基础功能配置
eacp:
  ## swagger 配置
  swagger:
    enabled: ${swagger.enabled:true}
    title: ${swagger.title:EACP平台XXX微服务}
    description: ${swagger.description:EACP平台XXX微服务接口文档}
    version: ${swagger.version:1.0}
    base-package: ${swagger.base-package:com.hanzhisoft.**.controller}
  ## 缓存管理配置
  cache-manager:
    configs:
      - key: xxx1
        second: 300
      - key: xxx2
        second: 1800
  ## 多租户配置(目前不适用)
  tenant:
    enable: ${tenant.enable:false}
    ignoreTables: ${tenant.ignoreTables}
